version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn --ignore-engines
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build

  test:
    docker:
      - image: circleci/node:10.0-browsers

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn --ignore-engines
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: yarn coverage

      - codecov/upload

workflows:
  version: 2
  push:
    jobs:
      - build
      - test:
          requires:
            - build
